name: Java CI and Dockerfile Validation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build

  validate-compose:
    runs-on: ubuntu-latest
    environment: env
    env:
      DB_USER: ${{ vars.DB_USER }}
      DB_PASSWORD: ${{ vars.DB_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose Configuration
        run: |
          sed -i 's/env_file:/env_file: ""/' docker-compose.yml
          DB_USER=$DB_USER
          DB_PASSWORD=$DB_PASSWORD
          docker-compose -f docker-compose.yml config --quiet
        
